### ISSUE TITLE
Occur these error at the time upload on App Store.

### ISSUE THREAD

**Issue by chankitDfire** [zoom/zoom-sdk-ios#1]
ERROR ITMS-90680: "The binary you uploaded was invalid."

ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "MyApp.app/MobileRTCResources.bundle/MobileRTC.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(machine code) and arm64(machine code), while the nested bundle Mach-O contains armv7(machine code) and arm64(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'MyApp.app/MobileRTCResources.bundle/MobileRTC.framework/MobileRTC' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

ERROR ITMS-90362: "Invalid Info.plist value. The value for the key 'MinimumOSVersion' in bundle MyApp.app/MobileRTCResources.bundle/MobileRTC.framework is invalid. The minimum value is 8.0"

ERROR ITMS-90124: "The binary is invalid. The executable type "OBJECT" is not valid. Only "EXECUTE" is permitted."

ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."

ERROR ITMS-90210: "Missing load commands. The executable at 'MyApp.app/MobileRTCResources.bundle/MobileRTC.framework' does not have the necessary load commands. Try rebuilding the app with the latest Xcode version. If you are using third party development tools, contact the provider."

**Comment by cleofasv** [comment]
We also encounter these same errors during upload to App Store. If possible, please advice on how to fix.

**Comment by devender54321** [comment]
@chankitDfire ,  we are facing same issue during app upload . Can you please suggest us how to fix these issue.


thanks
Devender

**Comment by Robusthxj** [comment]
For ERROR ITMS-90635，ERROR ITMS-90171， ERROR ITMS-90362 and ERROR ITMS-90210, seems that you did not integrate MobileRTC correctly into your project, MobileRTC.framework should not be included in MobileRTCResources.bundle, we suggested that both MobileRTC.framework and MobileRTCResources.bundle should be embedded into your main bundle, please refer to what we did in MobileRTCSample.

For ERROR ITMS-90124, please check "Mach-O Type" in Build Settings in your project, the value should be Executable.

Regards,
Robust

**Comment by devender54321** [comment]
Thanks @Robusthxj  for your guidance . our task completed .
