### ISSUE TITLE
Authorization success, but failure to join the room with password

### ISSUE THREAD

**Issue by xiu619544553** [zoom/zoom-sdk-ios#10]
Join the room return  MobileRTCMeetError_InvalidArguments.  I tried it on the computer. It was successful.

**Comment by Robusthxj** [comment]
Before joining meeting, MobileRTC need do sdkAuth at first. Did you do this?

BTW, join meeting just provide two parameters is OK, meeting number and display name.

Thanks,
Robust

**Comment by xiu619544553** [comment]
I add lib(MobileRTC.frame  MobileRTCResources.bundle) to my project! But,project always has error: "ld: '/Users/Dev/Desktop/MyProjectName/MyProjectName/WJApp/WJApp/lib/MobileRTC.framework/MobileRTC' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/Kingdev/Desktop/朴新教育/外教app/WJApp/WJApp/lib/MobileRTC.framework/MobileRTC' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"？

Can you help me ?

**Comment by xiu619544553** [comment]
I've solved it.

**Comment by alfonsocj** [comment]
@xiu619544553 how did you solve it?

'/Users/Dev/Desktop/MyProjectName/MyProjectName/WJApp/WJApp/lib/MobileRTC.framework/MobileRTC' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/Kingdev/Desktop/xxx/xxx/WJApp/WJApp/lib/MobileRTC.framework/MobileRTC' for architecture arm64

**Comment by crossgowhite** [comment]
@alfonsocj 
as it recommend, disable bitcode in build setting will help to u.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
