### ISSUE TITLE
Could I customize my own design page?

### ISSUE THREAD

**Issue by pantaopt** [zoom/zoom-sdk-ios#11]
Hello, i saw you write the vidio UI in the framework。Could I customize my own design page?

**Comment by Robusthxj** [comment]
Currently we cannot support to customize your own page. We are work on it now, the schedule may be April 2018.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
