### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by SoHotSoup** [zoom/zoom-sdk-ios#12]
Could you, please, make your SDK available on CocoaPods?
Here is the guide on how to do it: https://guides.cocoapods.org/making/making-a-cocoapod.html
Also, if you are open for contributions, I'm willing to do it, you will just need to add a tag and release it after me.

**Comment by SoHotSoup** [comment]
ping @zoomdevplatform

**Comment by WeiGuoZoom** [comment]
Thanks for providing this valuable feedback, currently we don't have plan and bandwidth to support this. Once we decide to add this on our roadmap, we will let you know.

**Comment by SoHotSoup** [comment]
Thanks @WeiGuoZoom. Let me know when this will be on your roadmap, I would like to contribute by doing that.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
