### ISSUE TITLE
Eraser stops working randomly during the Whiteboard session

### ISSUE THREAD

**Issue by kiranprazas** [zoom/zoom-sdk-ios#14]
We have integrated zoom sdk in iOS app & invoke the zoom sessions within the app. Users use annotation during the screen sharing. Sometimes in the session, eraser feature stops working. It happens randomly, 10-15 mins after the session start.

![image-8](https://user-images.githubusercontent.com/4449961/35553197-da71e702-05bc-11e8-8378-c22267b00d83.png)

**Comment by chaobaizoom** [comment]
@kiranprazas  1. sharing side can erase everything. 
2. Viewer can only erase something mark by self.
3. If viewer rejoin the meeting, cannot erase thing that mark in previous session.

**Comment by kiranprazas** [comment]
Thanks for update, 
The issue we are facing is from the 'Sharing Side".  Sharing user is able to erase initially (after starting the session), but suddenly in the middle of the session, the erase stops working. This is random behavior.

Thanks
Kiran Juikar

**Comment by chaobaizoom** [comment]
@kiranprazas  before erase stop working, what kind of action u had take? we try to reproduce issue.

**Comment by kiranprazas** [comment]
It's all random. During the session, it stops working randomly. Usually, it will be an audio session. Teachers will explain math problem during the session. There are no specific steps to reproduce. general feedback which we receive is after 10-15 mins of the session the eraser stops working.


Thanks
Kiran Juikar

**Comment by chaobaizoom** [comment]
@kiranprazas  thank you for feedback, we will try to reproduce issue.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
