### ISSUE TITLE
发起会议API

### ISSUE THREAD

**Issue by 54dujianchao** [zoom/zoom-sdk-ios#15]
（1）移动端可以未登陆，发起会议么

（2）关于sso登陆、获取Token没找到相关资料，希望得到帮助

**Comment by Robusthxj** [comment]
我们移动端SDK是支持登录和不登录两种方式，不登录的情况是使用API User的plan，通过REST API去获取用户信息，然后再通过REST API创建会议，然后再通过SDK的接口去起会。

关于SSO登录，我们官网上有些资料，请从这个链接获取：https://support.zoom.us/hc/en-us/articles/201363003-Getting-Started-with-SSO

**Comment by 54dujianchao** [comment]
1、登录sso网页，得到token字符串
2、BOOL sign = [[[MobileRTC sharedRTC] getAuthService] loginWithSSOToken:token];   返回true
3、NSDictionary *paramDict = @{
                                    kMeetingParam_UserType:@(MobileRTCUserType_SSOUser),
                                    kMeetingParam_IsAppShare:@(appShare)
                                    };
        
        MobileRTCMeetError ret = [ms startMeetingWithDictionary:paramDict];
一直转圈
 
想请问 ，sso登录后，怎么调用开始会议API

**Comment by Robusthxj** [comment]
SSO登录后，需要看- (void)onMobileRTCLoginReturn:(NSInteger)returnValue是否返回成功，如果不成功是开不了会的。

如果SSO登录成功后，开会参数里面只要带user type指定为sso user即可开即时会议。

**Comment by 54dujianchao** [comment]
可以了。
但是 ，会议开始后 ，获取该房间号 ，是在哪个回调方法中呢。

**Comment by Robusthxj** [comment]
有个@property (retain, nonatomic, readonly) NSString *ongoingMeetingNumber;在MobileRTCInviteHelper头文件内。

**Comment by 54dujianchao** [comment]
还想请教一个问题
每次sso登录， 都需要进入网页，输入用户名 跟 密码，这个有什么优化方案么。
比如只需第一次登录，之后自动登录。
（比较了下安卓webview，是会记住用户名、密码的。   iOS的webview，每次重启app后都需要得重新输入用户账号）

**Comment by Robusthxj** [comment]
如果之前login sso后，后面ios sdk会在sdk auth过做自动登录的，不需要再次手工登录，只要token未过期。

**Comment by 54dujianchao** [comment]
好的 ， 确实可以。
可以提供下  token 有效期多久吗

**Comment by Robusthxj** [comment]
我们存在本地的是Zoom回来的AccessToken理论上是不会过期的，除非将账户revoke了。

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
