### ISSUE TITLE
ld: Unable to insert branch island. No insertion point available. for architecture armv7

### ISSUE THREAD

**Issue by xiu619544553** [zoom/zoom-sdk-ios#16]
ld: Unable to insert branch island. No insertion point available. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xiu619544553** [comment]
An error occurred while replacing the SDK:
ld: Unable to insert branch island. No insertion point available. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

**Comment by chaobaizoom** [comment]
@xiu619544553  This is an issue with the full size of the app. 
You can try the following:
1. Strip debug symbols (build options), as debug symbols can increase the .o files a lot.
2. Code Refine & Split the code in more files.
3. Remove useless code in your project.
Hope it helpful for you.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
