### ISSUE TITLE
Accidental pop-up keyboard

### ISSUE THREAD

**Issue by 54dujianchao** [zoom/zoom-sdk-ios#19]
I found a problem, to join the meeting, sometimes the pop-up keyboard can't shut down.(a large number of users)

**Comment by Robusthxj** [comment]
You need to dismiss the keyboard which calling our interface. we do not handle this issue, because the join meeting UI is in your project.

**Comment by 54dujianchao** [comment]
for example,To join the conference room, pop-up input password box（SDK pop）.After the user input  completed, the last closed 。 Howevr to join the meeting, a new dialog pop(SDK pop).

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
