### ISSUE TITLE
Waiting view issue

### ISSUE THREAD

**Issue by medisean** [zoom/zoom-sdk-ios#2]
Join meeting waiting view is under the presented view.

**Comment by medisean** [comment]
I mean ZMProgressHUB is under the presented view when join meeting in the presented view.

**Comment by Robusthxj** [comment]
The correct feature flow is that you had better dismiss the view controller of joining meeting after clicked "Join meeting". Or the HUD will be covered.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
