### ISSUE TITLE
ZMHorizontalTableView NSRangeException

### ISSUE THREAD

**Issue by ldp940622** [zoom/zoom-sdk-ios#20]
Hi,
目前我们在使用Zoom时，在外网采集到了这样的闪退信息：
```
Fatal Exception: NSRangeException
-[ZMHorizontalTableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:]: section (2) beyond bounds (2).
```
看起来似乎是内部的越界导致的问题，但在目前的issue列表中未发现类似的问题。请查看下是否存在这样的隐性bug。

**Comment by Robusthxj** [comment]
出现问题的sdk是什么版本，我们新版本中做了些改进，能否更新下让客户再测试下

**Comment by ldp940622** [comment]
> 出现问题的sdk是什么版本，我们新版本中做了些改进，能否更新下让客户再测试下

目前从采集到的闪退信息来看，应该是`v4.1.12640.1103`和`v4.0.36208.0614`两个版本都出现了同样的问题。

**Comment by Robusthxj** [comment]
出问题的ios版本是ios11吗？我们最新的release改了个ios11的bug，你可以再更新给客户试试。

**Comment by ldp940622** [comment]
就目前采集到的数据来看，闪退的版本除了iOS 11+，iOS 10.3.3也出现了同样的问题。

**Comment by ldp940622** [comment]
就目前采集到的数据来看，闪退的版本除了iOS 11+，iOS 10.3.3也出现了同样的问题。

**Comment by ldp940622** [comment]
> 出问题的ios版本是ios11吗？我们最新的release改了个ios11的bug，你可以再更新给客户试试。

就采集的情况来看，不仅仅是iOS 11+，iOS 10.3.3也出现了同样的问题。

**Comment by Robusthxj** [comment]
OK, 我们看看能不能找到问题所在
