### ISSUE TITLE
获取头像

### ISSUE THREAD

**Issue by raomuming** [zoom/zoom-sdk-ios#21]
我们获取了user id和user token，在sdk没有login的情况下，我们通过user id和user token去起一个会议，但是会议中不显示用户的头像，请问这有什么解决办法吗。

**Comment by chaobaizoom** [comment]
使用userid和 user token起会不支持显示头像。你可以选择先登录，开会，会显示头像。

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
