### ISSUE TITLE
在自己的app中使用SDK，点击视频界面的“离开会议”或者“退出会议”的时候，没有响应，界面不会返回

### ISSUE THREAD

**Issue by huanglonghui** [zoom/zoom-sdk-ios#25]

**Comment by Robusthxj** [comment]
Did you use UIActionSheet block in your project? which will be impact on UIActionSheet in MobileRTC. We have found this issue, will fix in next release.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
