### ISSUE TITLE
[AppDelegate window] unrecognized selector sent to instance...

### ISSUE THREAD

**Issue by pavelsmelovsky** [zoom/zoom-sdk-ios#26]
Hi there!

In our AppDelegate we use window property with custom class. And when we try to join the meeting, app crash.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
