### ISSUE TITLE
Video does not show up unless you tap Switch Camera or Gallery View

### ISSUE THREAD

**Issue by briandutton** [zoom/zoom-sdk-ios#27]
I am using CallKit to ring the device and the begin a video call. This works fine if the device is unlocked with the app in the foreground and in the background. When the device is locked/asleep there is an issue with the video appearing when the call is answered.

After answering the call on a locked iPad, the meeting is started and connects. The Zoom UI displays properly but the rest of the screen is black. That participant's video is visible to the other party (person who called) but on the iPad there is no video visible of anyone.  After a couple of minutes, video will finally appear on the iPad. Tapping Gallery View or switching camera on the iPad will make the video appear immediately.

Another odd behavior is that CallKit shows the call as recording even though recording is disabled. This only happens when the call is answered from a locked screen, otherwise the call shows a normal (not recording) call.

**Comment by briandutton** [comment]
Still experiencing the issue where the video does not appear and user has to tap a button to make it show up. Any update on this? 

After answering the call on a locked iPad, the meeting is started and connects. The Zoom UI displays properly but the rest of the screen is black.

**Comment by chaobaizoom** [comment]
Please helo to insert following code in your appdelegate.

`- (void)applicationWillResignActive:(UIApplication *)application
{
    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
    // Use this method to pause ongoing tasks, disable timers, and throttle down OpenGL ES frame rates. Games should use this method to pause the game.
    
    [[MobileRTC sharedRTC] appWillResignActive];
}

- (void)applicationDidEnterBackground:(UIApplication *)application
{
    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later. 
    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    [[MobileRTC sharedRTC] appDidEnterBackgroud];
}

- (void)applicationWillEnterForeground:(UIApplication *)application
{
    // Called as part of the transition from the background to the inactive state; here you can undo many of the changes made on entering the background.
}

- (void)applicationDidBecomeActive:(UIApplication *)application
{
    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    
    [[MobileRTC sharedRTC] appDidBecomeActive];
}

- (void)applicationWillTerminate:(UIApplication *)application
{
    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
    [[MobileRTC sharedRTC] appWillTerminate];
}`

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
