### ISSUE TITLE
Lib `libstdc++.6.0.9.tbd` is deprecated by Apple on Xcode 10

### ISSUE THREAD

**Issue by leonardo-ferreira07** [zoom/zoom-sdk-ios#29]
Hello, 

The zoom SDK uses the `libstdc++.6.0.9.tbd` library, but this was deprecated on Xcode 10 and not available anymore, any updates on how this is going to be handled by zoom development team?

You can see more about [here](https://stackoverflow.com/questions/50694822/xcode-10-ios-12-does-not-contain-libstdc6-0-9) and also in Xcode 10 release notes.

Thank you.

**Comment by buffsldr** [comment]
I have the same issue as @leonardo-ferreira07

**Comment by chaobaizoom** [comment]
we are working on it, would support Xcode 10 in the coming release, thank you for feedback.

**Comment by leonardo-ferreira07** [comment]
Thank you very much for the feedback @chaobaizoom! 🎉 

Can you please let us know here when this release is out, then we can update our SDKs and close this one! 

Thank you again.

**Comment by chaobaizoom** [comment]
@leonardo-ferreira07  Sure, we will let u know when the release is ready.

**Comment by buffsldr** [comment]
Thank you.

**Comment by MaddyCoder** [comment]
Is the release ready?

**Comment by lvdaqian** [comment]
@chaobaizoom any update?

**Comment by chaobaizoom** [comment]
we are working on it, would support Xcode 10 in the coming release around the end of this month, thank you for feedback.

**Comment by jtweeks** [comment]
Also waiting on this update

**Comment by chaobaizoom** [comment]
Here is the beta build supported Xcode 10, the official build would be released at end of October.

https://app.box.com/s/jhbbv5kjmhx6c55lo9ko27of86kh6o68

**Comment by junya100** [comment]
I have tested the beta build. It works correctly! Thanks.

**Comment by chaobaizoom** [comment]
@leonardo-ferreira07 @buffsldr  @MaddyCoder  @lvdaqian  feel free to download beta build that support xcode10. the official build would be released at end of October.

**Comment by leonardo-ferreira07** [comment]
Thank you very much @chaobaizoom!

**Comment by StephShaw-Veeva** [comment]
@chaobaizoom Has the official build been released?

**Comment by chaobaizoom** [comment]
@StephShaw-Veeva  no yet.

**Comment by SamboVisal** [comment]
I have been waiting for it to be released

**Comment by ananthasivanvk** [comment]
I am also waiting for this.

**Comment by pavelsmelovsky** [comment]
We also waiting for new release supporting Xcode 10.

We can not work properly with current MobileRTC framework in Xcode 10 and iOS 12 Simulator. App on simulator crashed, IBDesignable views cannot be drawn, because it also use iOS 12 simulator for rendering.

@chaobaizoom 
Are you have internal task for your developers to solve this problem, or not?

**Comment by 1284115201** [comment]
I'm waiting, and I've been waiting for a long time.

**Comment by jtweeks** [comment]
We need this resolved immediately, it has been 2 months already and our production deployments are being held back.  How do you expect to keep customers licensing your products when you hold their schedules hostage.  This should have been the number 1 priority for Zoom once it showed up.  Apple forces users to their newest Xcode versions to support their latest Os releases, Zoom is going to have to keep up.

**Comment by carsonzoom** [comment]
Hi everyone, thanks for using our SDK. The issue mentioned in the title has been resolved in our October release [v4.1.34076.1024](https://github.com/zoom/zoom-sdk-ios/releases/tag/v4.1.34076.1024). Please let us know if you have any other questions. Thank you very much.
