### ISSUE TITLE
Support bitcode

### ISSUE THREAD

**Issue by medisean** [zoom/zoom-sdk-ios#3]
I found the framework doesn't support bitcode, right?

**Comment by julio-rivera** [comment]
+1

**Comment by Robusthxj** [comment]
Yes, iOS SDK cannot bitcode because some of third party libraries cannot support it.

**Comment by blainesolomon** [comment]
Please don't force developers to drop support for Bitcode

**Comment by dhruv-jindal** [comment]
+1

**Comment by chaobaizoom** [comment]
@blainesolomon  @dhruv-jindal  thanks for your info. Zoom product are very performance sensitive though, some part is assembly level optimization. That’s why we donot bitcode now. Anyway, we will keep research on it.

**Comment by rk85097** [comment]
+1

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
