### ISSUE TITLE
TermSBPTUIModule(Cmm::ICmmMessageQueueClient*) 

### ISSUE THREAD

**Issue by ldp940622** [zoom/zoom-sdk-ios#30]
iOS 12，出现
```swift
18 | UIKitCore | -[UIView(CALayerDelegate) drawLayer:inContext:] + 464
-- | -- | --
19 | QuartzCore | -[CALayer drawInContext:] + 296
20 | QuartzCore | CABackingStoreUpdate_ + 176
21 | QuartzCore | invocation function for block in CA::Layer::display_() + 52
22 | QuartzCore | -[CALayer _display] + 1540
23 | QuartzCore | -[CALayer renderInContext:] + 184
24 | xxx| TermSBPTUIModule(Cmm::ICmmMessageQueueClient*) + 4360295604
```
死循环导致应用闪退的问题，且`TermSBPTUIModule(Cmm::ICmmMessageQueueClient*) `这条信息似乎在每一个线程中都出现，且最后暴露闪退的代码也是这一条。

麻烦查看一下是否是我们的使用问题，还是代码问题。

**Comment by chaobaizoom** [comment]
请用最新的包试试看

**Comment by ldp940622** [comment]
@chaobaizoom 使用最新的包之后最上面的问题的确好像是没有了

但另外发现自从使用Zoom以来一直会有`gpus_ReturnNotPermittedKillClient`这种类型的闪退，查阅资料给出的结果表明出现这个问题的原因是因为当APP在后台时，OpenGL依然在渲染导致的闪退，请问这是我们使用的方法问题还是什么原因？

**Comment by chaobaizoom** [comment]
当程序切到后天，回复到前台， sdk都有提供相对应的接口，app必须要调用对应的接口，否则有可能会遇到你描述的问题，具体的接口，已经使用你可以参照sample的appdelegate.

**Comment by ldp940622** [comment]
这些接口目前在我们的应用里都是调用了的，和Sample工程中是一样的，但还是出现了这个问题。

**Comment by chaobaizoom** [comment]
- (void)applicationWillResignActive:(UIApplication *)application
{
    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
    // Use this method to pause ongoing tasks, disable timers, and throttle down OpenGL ES frame rates. Games should use this method to pause the game.
    
    [[MobileRTC sharedRTC] appWillResignActive];
}

- (void)applicationDidEnterBackground:(UIApplication *)application
{
    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later. 
    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    [[MobileRTC sharedRTC] appDidEnterBackgroud];
}

- (void)applicationWillEnterForeground:(UIApplication *)application
{
    // Called as part of the transition from the background to the inactive state; here you can undo many of the changes made on entering the background.
}

- (void)applicationDidBecomeActive:(UIApplication *)application
{
    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    
    [[MobileRTC sharedRTC] appDidBecomeActive];
}

- (void)applicationWillTerminate:(UIApplication *)application
{
    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
    [[MobileRTC sharedRTC] appWillTerminate];
}

这些接口，app层是否已经调用？

**Comment by ldp940622** [comment]
是的，所有`MobileRTC.shared().appxxxx`相关的接口都已经在这些方法中调用了。

**Comment by chaobaizoom** [comment]
好的，请提供crash dump文件，已经你使用的sdk version版本号。

**Comment by ldp940622** [comment]
[crash_dump.zip](https://github.com/zoom/zoom-sdk-ios/files/2427324/crash_dump.zip)
SDK的版本号应该是v4.1.32183.0910

**Comment by chaobaizoom** [comment]
issue_40_crash_.txt这个crash 是你自己的app 的crash.
issue_532_crash_.txt 这个crash，我们会在下个release fix调这个问题。:)
Thank you so much for the info.

**Comment by ldp940622** [comment]
sry, 给错了一个。。
[issue_519_crash.txt](https://github.com/zoom/zoom-sdk-ios/files/2427363/issue_519_crash.txt)
可以看一下这个和532是不是也是相同的，thx.

**Comment by chaobaizoom** [comment]
是的，问题是一样的，我们这边已经修改了这个问题，马上的release会改掉。

**Comment by ldp940622** [comment]
请问这个 issue 里提到的问题，v4.1.34076.1024 里修复了吗？

**Comment by ldp940622** [comment]
@chaobaizoom

**Comment by chaobaizoom** [comment]
@ldp940622  请试试新的库，请注意SDK 的delegate 是assgin属性， 请确保你的对象被释放的时候，将delegate属性设置为nil, 否则会crash.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)

**Comment by kirti301290** [comment]
Hello
Zoom sdk Version 	v4.1.34076.1024

today i getting issue in Iphone  X device and it working on iPhone 6 and iPhone 7
here is attached 
[com.deepfood.tasktower_issue_18_crash_49d4d4f7c6c945f294c37954cb206b3a_DNE_0_v2.txt](https://github.com/zoom/zoom-sdk-ios/files/2612135/com.deepfood.tasktower_issue_18_crash_49d4d4f7c6c945f294c37954cb206b3a_DNE_0_v2.txt)
