### ISSUE TITLE
can't start a meeting  it showing  "Waiting for the host to start the meeting"

### ISSUE THREAD

**Issue by kirti301290** [zoom/zoom-sdk-ios#31]
Hello
it was working previous version v4.1.12640.1103 
after upgraded new SDK  version v4.1.32183.0910  then can not start meeting it showing every time 
"Waiting for the host to start the meeting"
how can get kSDKUserToken , kZAK  value  which is given from Sample demo in new SDK version

**Comment by kirti301290** [comment]
@chaobaizoom  version v1 will expire end of this months 
you can check in https://zoom.github.io/api-v1/

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
