### ISSUE TITLE
Integration issue with Xcode 10.0, swift 4.2

### ISSUE THREAD

**Issue by khimani91** [zoom/zoom-sdk-ios#33]
Xcode 10.0 and swift 4.2 
Error occur as follwing...

Undefined symbols for architecture x86_64:
"_OBJC_CLASS_$_ClassNmae", referenced from: objc-class-ref in SomeClassName" . . .

d: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by khimani91** [comment]
Error: In XCode 10.0

dyld: Library not loaded: @rpath/MobileRTC.framework/MobileRTC
  Referenced from: /Users/.../ZoomDemo
  Reason: image not found

**Comment by chaobaizoom** [comment]
iOS SDK has switched into dynamic lib, so you should link SDK as embedded binaries. For more detail, you can refer to SDK example of the latest version on Github. Thank for choose zoom.
For info, you can refer to https://marketplace.zoom.us/docs/guides/zoom-sdks/ios

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue has been resolved in the latest version of our SDK ([v4.1.34076.1024](https://github.com/zoom/zoom-sdk-ios/releases/tag/v4.1.34076.1024)). If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
