### ISSUE TITLE
About v4.1.34076.1024

### ISSUE THREAD

**Issue by 1284115201** [zoom/zoom-sdk-ios#34]
dyld: Library not loaded: @rpath/MobileRTC.framework/MobileRTC
  Referenced from: /var/containers/Bundle/Application/04B07893-904A-4088-861A-3182A3D02CD6/XXX.app/XXX
  Reason: image not found

**Comment by 1284115201** [comment]
@chaobaizoom

**Comment by chaobaizoom** [comment]
@1284115201  the latest SDK is one dynamic  framework, 
The MobileRTC.framework should be imported into:
Link Binary With Libraries
Embedded Binaries 
you can refer to SDK Sample.
