### ISSUE TITLE
sample code import failure, if disk partition is case sensitive

### ISSUE THREAD

**Issue by sanhue0302** [zoom/zoom-sdk-ios#37]
if sample is run on a disk that disk partition is case sensitive

compile will get error 
on MainViewController+MeetingServiceDelegate.h:10

```
#import <Mobilertc/MobileRTCMeetingDelegate.h>
```

should fix to 

```
#import <MobileRTC/MobileRTCMeetingDelegate.h>
```

**Comment by chaobaizoom** [comment]
@sanhue0302  can you help to provide more detail here?
