### ISSUE TITLE
crash on chat

### ISSUE THREAD

**Issue by hbcffc** [zoom/zoom-sdk-ios#4]
When I run the sample app, it always crashed on chat either send a message or receive a message.
here is the exception:
CALayer position contains NaN: [-21 nan]
(
	0   CoreFoundation                      0x0000000181177e70 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000180688528 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000181177da0 <redacted> + 0
	3   QuartzCore                          0x000000018528288c <redacted> + 156
	4   QuartzCore                          0x0000000185274a0c <redacted> + 44
	5   GPUToolsCore                        0x0000000101e89abc _ZL19CALayer_setPositionP7CALayerP13objc_selector7CGPoint + 32
	6   QuartzCore                          0x000000018527506c <redacted> + 444
	7   UIKit                               0x000000018abafe48 <redacted> + 356
	8   UIKit                               0x000000018abc37f8 <redacted> + 180
	9   UIKit                               0x000000018abcdc9c <redacted> + 596
	10  CoreFoundation                      0x0000000181055194 <redacted> + 444
	11  UIKit                               0x000000018abbbf4c <redacted> + 160
	12  UIKit                               0x000000018abafef8 <redacted> + 532
	13  UIKit                               0x000000018abd4224 <redacted> + 156
	14  UIKit                               0x000000018b781538 <redacted> + 56
	15  UIKit                               0x000000018b781238 <redacted> + 492
	16  UIKit                               0x000000018ac51498 <redacted> + 192
	17  MobileRTCSample                     0x000000010056321c _Z10ios_getpidv + 254400
	18  MobileRTCSample                     0x0000000100562fac _Z10ios_getpidv + 253776
	19  UIKit                               0x000000018abb3630 <redacted> + 1256
	20  QuartzCore                          0x000000018527a310 <redacted> + 184
	21  QuartzCore                          0x000000018527e3c8 <redacted> + 332
	22  UIKit                               0x000000018abc84a0 <redacted> + 548
	23  UIKit                               0x000000018abc4234 <redacted> + 104
	24  UIKit                               0x000000018aee7474 <redacted> + 1104
	25  UIKit                               0x000000018aee77ac <redacted> + 80
	26  UIKit                               0x000000018aec82bc <redacted> + 2144
	27  UIKit                               0x000000018ac87710 <redacted> + 140
	28  UIKit                               0x000000018abb3630 <redacted> + 1256
	29  QuartzCore                          0x000000018527a310 <redacted> + 184
	30  QuartzCore                          0x000000018527e3c8 <redacted> + 332
	31  QuartzCore                          0x00000001851ee4fc <redacted> + 336
	32  QuartzCore                          0x000000018521498c <redacted> + 540
	33  UIKit                               0x000000018aba8ed0 <redacted> + 256
	34  CoreFoundation                      0x0000000181121594 <redacted> + 32
	35  CoreFoundation                      0x000000018111f03c <redacted> + 412
	36  CoreFoundation                      0x000000018111f520 <redacted> + 1076
	37  CoreFoundation                      0x0000000181041bf0 CFRunLoopRunSpecific + 436
	38  GraphicsServices                    0x0000000182e9bfac GSEventRunModal + 100
	39  UIKit                               0x000000018ac19ec4 UIApplicationMain + 208
	40  MobileRTCSample                     0x00000001004b052c main + 116
	41  libdyld.dylib                       0x0000000180b661e0 <redacted> + 4
)

**Comment by hbcffc** [comment]
By the way, this crash happened on iOS 11 beta device. when I use iOS 10 device, chat is OK.

**Comment by Robusthxj** [comment]
This is caused by iOS 11 compatibility, we will fix it in September Release

**Comment by hbcffc** [comment]
Will you fix the bug this week?

**Comment by FerasFarhan** [comment]
Any update on this issue?

It is still crashing on the chat

**Comment by Robusthxj** [comment]
We will fix it in next release, the release date is about early November.

**Comment by Robusthxj** [comment]
Please download the latest iOS mobileRTC from github, and have a test.

**Comment by hbcffc** [comment]
The new version sdk is OK, thanks.
