### ISSUE TITLE
iOS 11 preview bug

### ISSUE THREAD

**Issue by medisean** [zoom/zoom-sdk-ios#6]
In iOS 11 devices,  I can't see video preview image, it's black.  
![wechatimg7](https://user-images.githubusercontent.com/6093631/32720650-cd8ca584-c829-11e7-8473-4650d9634faf.jpeg)

**Comment by Robusthxj** [comment]
Please use the latest released iOS mobileRTC and have a try. The issue existed in old mobileRTC if build with Xcode 9.

**Comment by medisean** [comment]
Thank you

**Comment by FerasFarhan** [comment]
Still have this issue using iPhone 7 plus with iOS 11.1.2

**Comment by Robusthxj** [comment]
You can duplicate this issue with our MobileRTCSample project? BTW, did you download the latest iOS mobileRTC.framework from the following link (zoom-ios-mobilertc-with-emulator.zip)?
https://github.com/zoom/zoom-sdk-ios/releases

**Comment by medisean** [comment]
Yes, download the latest framework will solve the problem
