### ISSUE TITLE
the MobileRTCSample could not run

### ISSUE THREAD

**Issue by 54dujianchao** [zoom/zoom-sdk-ios#7]
when run，some wrong

d: warning: ignoring file ../lib/mobileRTC.framework/mobileRTC, missing required architecture x86_64 in file ../lib/mobileRTC.framework/mobileRTC (2 slices)
Undefined symbols for architecture x86_64:
  "_kMeetingParam_UserID", referenced from:
      -[MainViewController startMeeting:] in MainViewController.o
  "_kMeetingParam_IsAppShare", referenced from:
      -[MainViewController startMeeting:] in MainViewController.o
  "_kMeetingParam_MeetingNumber", referenced from:
      -[MainViewController startMeeting:] in MainViewController.o
      -[MainViewController joinMeeting:withPassword:] in MainViewController.o
  "_kMeetingParam_MeetingPassword", referenced from:
      -[MainViewController joinMeeting:withPassword:] in MainViewController.o
  "_kMeetingParam_Username", referenced from:
      -[MainViewController startMeeting:] in MainViewController.o
      -[MainViewController joinMeeting:withPassword:] in MainViewController.o
  "_OBJC_CLASS_$_MobileRTC", referenced from:
      objc-class-ref in InviteViewController.o
      objc-class-ref in AppDelegate.o
      objc-class-ref in LanguaguePickerViewController.o
      objc-class-ref in ScheduleTableViewController.o
      objc-class-ref in MeetingSettingsViewController.o
      objc-class-ref in MainViewController.o
      objc-class-ref in SettingsViewController.o
      ...
  "_kMeetingParam_UserType", referenced from:
      -[MainViewController startMeeting:] in MainViewController.o
  "_kMeetingParam_UserToken", referenced from:
      -[MainViewController startMeeting:] in MainViewController.o
  "_OBJC_CLASS_$_MobileRTCInviteHelper", referenced from:
      objc-class-ref in InviteViewController.o
      objc-class-ref in MainViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Robusthxj** [comment]
Seems that you build your project with device only mobileRTC.framework, please download mobileRTC.framework with simulator and device, the link as following:
https://github.com/zoom/zoom-sdk-ios/releases

**Comment by 54dujianchao** [comment]
thanks , it works

**Comment by 54dujianchao** [comment]
Some new problems, the demo shows "the SDK authorization failure, error code: 5"

**Comment by 54dujianchao** [comment]
Document indicating： Meeting is at capacity | 5 | None
I don't know how to deal with

**Comment by Robusthxj** [comment]
Please check your network, error code: 5 is mostly caused by network issue.

**Comment by 54dujianchao** [comment]
Testing by the company and China unicom 4G, still suggests "the SDK authorization failure, the error code: 5"。
Want to ping your service address, to test the network of our side.
Can please provide an HTTP address

**Comment by Robusthxj** [comment]
which domain do you set while integrate with iOS mobileRTC? you can ping the domain in you local.

**Comment by 54dujianchao** [comment]
thanks ， But there is two problems。  

1、I use the simulator to run，Power is stuck 。 Can use the simulator run ？
2、I use a real machine operation，Cannot compile，Prompt the following error
Undefined symbols for architecture arm64:
  "_VTDecompressionSessionInvalidate", referenced from:
      l85901 in MobileRTC
  "_VTDecompressionSessionCanAcceptFormatDescription", referenced from:
      l85905 in MobileRTC
  "_VTDecompressionSessionCreate", referenced from:
      l85905 in MobileRTC
      l85908 in MobileRTC
  "_VTDecompressionSessionDecodeFrame", referenced from:
      l85897 in MobileRTC
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Robusthxj** [comment]
Please add VideoToolbox.framework into your project. BTW, mobileRTCSample can be run in the simulator if you downloaded mobileRTC.framework with device and simulator.

**Comment by 54dujianchao** [comment]
When calling authorization，
methods “onMobileRTCAuthReturn” return "MobileRTCAuthError_Unknown"

Have any relevant documents  
or
How to do

**Comment by 54dujianchao** [comment]
1、// Sink auth event
   - (void)onMobileRTCAuthReturn:(MobileRTCAuthError)returnValue
    return MobileRTCAuthError_Success
2、then  call 
       BOOL ret = [authService loginWithEmail:@"xxxxxxxx" password:@"xxxxx"];
     Always returns NO

3、// Sink Event 
- (void)onMobileRTCLoginReturn:(NSInteger) returnValue 
Always returns 0

Methods 2, 3, the return value is what reason is caused

Couldn't find the related  document

**Comment by Robusthxj** [comment]
If you are in China, please join the following meeting, we can check it in meeting: https://success.zoom.us/my/robusthu

**Comment by 54dujianchao** [comment]
Thank you very much

**Comment by 54dujianchao** [comment]
可以自定义视频会议样式吗。比如：
去掉 “共享”、“参与人”
