### ISSUE TITLE
the MobileRTCSample could not run

### ISSUE THREAD

**Issue by medisean** [zoom/zoom-sdk-ios#8]
When set the kZoomSDKAppKey, kZoomSDKAppSecret and kZoomSDKDomain in demo, Click Start meeting return: onMeetNow ret:150. Zoom meeting failed.

Device: iPhone 7
Version: iOS 11.1
Xcode: 9.1

**Comment by Robusthxj** [comment]
Which parameters are you set for starting meeting, 150 means invalid parameters while starting meeting.
BTW, we have three user types, and each of user type should use different parameters to start meeting. For API user, we need userid, token, user type, user name and meeting number to start meeting; For Zoom user/SSO user, we need customer to login with work email or login with SSO at first, then need userid and meeting number (optional) to start meeting.

**Comment by medisean** [comment]
I am a Zoom User.  I login AppDelegate first, and start meeting then. How to get userid? Userid is required?

**Comment by medisean** [comment]
I fix the problem. Set kMeetingParam_UserType to MobileRTCUserType_SSOUser. Thank you

**Comment by Robusthxj** [comment]
set the kZoomSDKAppKey, kZoomSDKAppSecret and kZoomSDKDomain is just for SDK auth, it does not mean to login. For zoom user, you can call interface "- (BOOL)loginWithEmail:(NSString*)email password:(NSString*)password" to login with email after SDK auth. For API user, you can get user id and token by REST API, then to start meeting.

**Comment by Robusthxj** [comment]
If you are a zoom user, please set the user type to kMeetingParam_ZoomUser; if you are a SSO user, please set user type to kMeetingParam_SSOUser; if you are an API user, please set user type to kMeetingParam_APIUser
