### ISSUE TITLE
Why can't start a meeting with error code 150?

### ISSUE THREAD

**Issue by yanyufzf00** [zoom/zoom-sdk-ios#9]
I have already registered a developer account and login in demo app. And then I set kMeetingParam_UserType, kMeetingParam_MeetingNumber, kMeetingParam_IsAppShare params. Why always tell me MobileRTCMeetError_InvalidArguments. Is the kMeetingParam_MeetingNumber's value wrong? What should I do to find a right meeting number?

**Comment by Robusthxj** [comment]
If you login with work email in MobileRTC, you just set parameters kMeetingParam_UserType for instant meeting; If you want to start a scheduled meeting with meeting number, you can create a scheduled meeting by REST API.
